-- MySQL Script generated by MySQL Workbench
-- Tue Feb 24 18:24:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Puzzles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puzzles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `objective` VARCHAR(45) NOT NULL,
  `playerSide` VARCHAR(6) NOT NULL,
  `rounds` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Players` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rating` INT NULL,
  `RU` INT NULL,
  `games_played` VARCHAR(45) NULL,
  `Countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Players_Countries1_idx` (`Countries_id` ASC) VISIBLE,
  CONSTRAINT `fk_Players_Countries1`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isOfficial` TINYINT(1) NOT NULL,
  `isRated` TINYINT(1) NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GameTypes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `time_increment` INT NULL,
  `time_reserve` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matches` (
  `id` INT NOT NULL,
  `termination_type` VARCHAR(45) NOT NULL,
  `Moves_moves` VARCHAR(45) NOT NULL,
  `Moves_id` INT NOT NULL,
  `player_id_silver` INT NOT NULL,
  `player_id_gold` INT NOT NULL,
  `match_result` VARCHAR(45) NOT NULL,
  `Events_id` INT NOT NULL,
  `GameTypes_name` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Matches_copy1_Players_copy11_idx` (`player_id_silver` ASC) VISIBLE,
  INDEX `fk_Matches_copy1_Players_copy12_idx` (`player_id_gold` ASC) VISIBLE,
  INDEX `fk_Matches_copy1_Events_copy11_idx` (`Events_id` ASC) VISIBLE,
  INDEX `fk_Matches_copy1_GameTypes_copy11_idx` (`GameTypes_name` ASC) VISIBLE,
  CONSTRAINT `fk_Matches_copy1_Players_copy11`
    FOREIGN KEY (`player_id_silver`)
    REFERENCES `mydb`.`Players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_copy1_Players_copy12`
    FOREIGN KEY (`player_id_gold`)
    REFERENCES `mydb`.`Players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_copy1_Events_copy11`
    FOREIGN KEY (`Events_id`)
    REFERENCES `mydb`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_copy1_GameTypes_copy11`
    FOREIGN KEY (`GameTypes_name`)
    REFERENCES `mydb`.`GameTypes` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Position` (
  `id` INT NOT NULL,
  `color` VARCHAR(6) NOT NULL,
  `piece` VARCHAR(4) NOT NULL,
  `cordinate` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moves` (
  `id` INT NOT NULL,
  `turn` INT NOT NULL,
  `sequence` INT NOT NULL,
  `direction` VARCHAR(1) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `Matches_copy1_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Moves_copy1_Matches_copy11_idx` (`Matches_copy1_id` ASC) VISIBLE,
  INDEX `fk_Moves_position1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_Moves_copy1_Matches_copy11`
    FOREIGN KEY (`Matches_copy1_id`)
    REFERENCES `mydb`.`Matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moves_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OpeningsByMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OpeningsByMatch` (
  `id` INT NOT NULL,
  `Matches_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Openings_Matches1_idx` (`Matches_id` ASC) VISIBLE,
  INDEX `fk_Openings_position1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_Openings_Matches1`
    FOREIGN KEY (`Matches_id`)
    REFERENCES `mydb`.`Matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Openings_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OpeningsByPuzzle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OpeningsByPuzzle` (
  `id` INT NOT NULL,
  `position_id` INT NOT NULL,
  `puzzles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Openings_copy1_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_Openings_copy1_puzzles1_idx` (`puzzles_id` ASC) VISIBLE,
  CONSTRAINT `fk_Openings_copy1_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Openings_copy1_puzzles1`
    FOREIGN KEY (`puzzles_id`)
    REFERENCES `mydb`.`Puzzles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solutions` (
  `id` INT NOT NULL,
  `turn` INT NOT NULL,
  `sequence` INT NOT NULL,
  `direction` VARCHAR(1) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `position_id` INT NOT NULL,
  `puzzles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Solution_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_Solution_puzzles1_idx` (`puzzles_id` ASC) VISIBLE,
  CONSTRAINT `fk_Solution_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solution_puzzles1`
    FOREIGN KEY (`puzzles_id`)
    REFERENCES `mydb`.`Puzzles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
